throw "Error";

// Since we havent accounted for the above error, our program has crashed and will not continue on from the above error to any code below it

console.log("Code under error");
